DROP TABLE IF EXISTS session CASCADE;
DROP TABLE IF EXISTS subject CASCADE;
DROP TABLE IF EXISTS student CASCADE;
DROP TABLE IF EXISTS stud_groups CASCADE;
DROP TABLE IF EXISTS chair CASCADE;
DROP TABLE IF EXISTS faculty CASCADE;